// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type DefaultFilterInput struct {
	Search     *string                       `json:"search,omitempty"`
	Pagination *DefaultFilterPaginationInput `json:"pagination,omitempty"`
	Sort       *DefaultFilterSortInput       `json:"sort,omitempty"`
}

type DefaultFilterPaginationInput struct {
	Page   *int                        `json:"page,omitempty"`
	Length *FilterPaginationLengthEnum `json:"length,omitempty"`
}

type DefaultFilterSortInput struct {
	Field      *string           `json:"field,omitempty"`
	By         *FilterSortByEnum `json:"by,omitempty"`
	NullsFirst *bool             `json:"nullsFirst,omitempty"`
}

type MutateSomethingDto struct {
	ID       int      `json:"id"`
	SomeEnum SomeEnum `json:"SomeEnum"`
}

type Mutation struct {
}

type PaginationInfo struct {
	Count int `json:"count"`
}

type Query struct {
}

type Something struct {
	ID       string   `json:"id"`
	SomeEnum SomeEnum `json:"SomeEnum"`
}

type FilterPaginationLengthEnum string

const (
	FilterPaginationLengthEnumTen         FilterPaginationLengthEnum = "TEN"
	FilterPaginationLengthEnumFifteen     FilterPaginationLengthEnum = "FIFTEEN"
	FilterPaginationLengthEnumTwenty      FilterPaginationLengthEnum = "TWENTY"
	FilterPaginationLengthEnumTwentyFive  FilterPaginationLengthEnum = "TWENTY_FIVE"
	FilterPaginationLengthEnumThirty      FilterPaginationLengthEnum = "THIRTY"
	FilterPaginationLengthEnumThirtyFive  FilterPaginationLengthEnum = "THIRTY_FIVE"
	FilterPaginationLengthEnumForty       FilterPaginationLengthEnum = "FORTY"
	FilterPaginationLengthEnumFortyFive   FilterPaginationLengthEnum = "FORTY_FIVE"
	FilterPaginationLengthEnumFifty       FilterPaginationLengthEnum = "FIFTY"
	FilterPaginationLengthEnumFiftyFive   FilterPaginationLengthEnum = "FIFTY_FIVE"
	FilterPaginationLengthEnumSixty       FilterPaginationLengthEnum = "SIXTY"
	FilterPaginationLengthEnumSixtyFive   FilterPaginationLengthEnum = "SIXTY_FIVE"
	FilterPaginationLengthEnumSeventy     FilterPaginationLengthEnum = "SEVENTY"
	FilterPaginationLengthEnumSeventyFive FilterPaginationLengthEnum = "SEVENTY_FIVE"
	FilterPaginationLengthEnumEighty      FilterPaginationLengthEnum = "EIGHTY"
	FilterPaginationLengthEnumEightyFive  FilterPaginationLengthEnum = "EIGHTY_FIVE"
	FilterPaginationLengthEnumNinety      FilterPaginationLengthEnum = "NINETY"
	FilterPaginationLengthEnumNinetyFive  FilterPaginationLengthEnum = "NINETY_FIVE"
	FilterPaginationLengthEnumOneHundred  FilterPaginationLengthEnum = "ONE_HUNDRED"
)

var AllFilterPaginationLengthEnum = []FilterPaginationLengthEnum{
	FilterPaginationLengthEnumTen,
	FilterPaginationLengthEnumFifteen,
	FilterPaginationLengthEnumTwenty,
	FilterPaginationLengthEnumTwentyFive,
	FilterPaginationLengthEnumThirty,
	FilterPaginationLengthEnumThirtyFive,
	FilterPaginationLengthEnumForty,
	FilterPaginationLengthEnumFortyFive,
	FilterPaginationLengthEnumFifty,
	FilterPaginationLengthEnumFiftyFive,
	FilterPaginationLengthEnumSixty,
	FilterPaginationLengthEnumSixtyFive,
	FilterPaginationLengthEnumSeventy,
	FilterPaginationLengthEnumSeventyFive,
	FilterPaginationLengthEnumEighty,
	FilterPaginationLengthEnumEightyFive,
	FilterPaginationLengthEnumNinety,
	FilterPaginationLengthEnumNinetyFive,
	FilterPaginationLengthEnumOneHundred,
}

func (e FilterPaginationLengthEnum) IsValid() bool {
	switch e {
	case FilterPaginationLengthEnumTen, FilterPaginationLengthEnumFifteen, FilterPaginationLengthEnumTwenty, FilterPaginationLengthEnumTwentyFive, FilterPaginationLengthEnumThirty, FilterPaginationLengthEnumThirtyFive, FilterPaginationLengthEnumForty, FilterPaginationLengthEnumFortyFive, FilterPaginationLengthEnumFifty, FilterPaginationLengthEnumFiftyFive, FilterPaginationLengthEnumSixty, FilterPaginationLengthEnumSixtyFive, FilterPaginationLengthEnumSeventy, FilterPaginationLengthEnumSeventyFive, FilterPaginationLengthEnumEighty, FilterPaginationLengthEnumEightyFive, FilterPaginationLengthEnumNinety, FilterPaginationLengthEnumNinetyFive, FilterPaginationLengthEnumOneHundred:
		return true
	}
	return false
}

func (e FilterPaginationLengthEnum) String() string {
	return string(e)
}

func (e *FilterPaginationLengthEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterPaginationLengthEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterPaginationLengthEnum", str)
	}
	return nil
}

func (e FilterPaginationLengthEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FilterSortByEnum string

const (
	FilterSortByEnumAsc  FilterSortByEnum = "ASC"
	FilterSortByEnumDesc FilterSortByEnum = "DESC"
)

var AllFilterSortByEnum = []FilterSortByEnum{
	FilterSortByEnumAsc,
	FilterSortByEnumDesc,
}

func (e FilterSortByEnum) IsValid() bool {
	switch e {
	case FilterSortByEnumAsc, FilterSortByEnumDesc:
		return true
	}
	return false
}

func (e FilterSortByEnum) String() string {
	return string(e)
}

func (e *FilterSortByEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterSortByEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterSortByEnum", str)
	}
	return nil
}

func (e FilterSortByEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SomeEnum string

const (
	SomeEnumHello SomeEnum = "Hello"
	SomeEnumWorld SomeEnum = "World"
)

var AllSomeEnum = []SomeEnum{
	SomeEnumHello,
	SomeEnumWorld,
}

func (e SomeEnum) IsValid() bool {
	switch e {
	case SomeEnumHello, SomeEnumWorld:
		return true
	}
	return false
}

func (e SomeEnum) String() string {
	return string(e)
}

func (e *SomeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SomeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SomeEnum", str)
	}
	return nil
}

func (e SomeEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
