package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"app/internal/core/graph/model"
	"context"
)

// GetAppToken is the resolver for the getAppToken field.
func (r *mutationResolver) GetAppToken(ctx context.Context) (*model.AppToken, error) {
	return r.AuthModule.API.GetAppToken(ctx)
}
