package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"app/internal/core/graph"
	"app/internal/core/graph/model"
	"context"
)

// CreateDomainItem is the resolver for the createDomainItem field.
func (r *mutationResolver) CreateDomainItem(ctx context.Context, input model.CreateDomainItemInput) (*model.DomainItem, error) {
	return r.DomainItemModule.API.CreateDomainItem(ctx, input.Name)
}

// UpdateDomainItem is the resolver for the updateDomainItem field.
func (r *mutationResolver) UpdateDomainItem(ctx context.Context, input model.UpdateDomainItemInput) (*model.DomainItem, error) {
	return r.DomainItemModule.API.UpdateDomainItem(ctx, input.ID, input.Name, input.Status)
}

// DeleteDomainItem is the resolver for the deleteDomainItem field.
func (r *mutationResolver) DeleteDomainItem(ctx context.Context, id string) (*model.DeleteDomainItemResponse, error) {
	success, err := r.DomainItemModule.API.DeleteDomainItem(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.DeleteDomainItemResponse{Success: success}, nil
}

// DomainItem is the resolver for the domainItem field.
func (r *queryResolver) DomainItem(ctx context.Context, id string) (*model.DomainItem, error) {
	return r.DomainItemModule.API.DomainItem(ctx, id)
}

// DomainItems is the resolver for the domainItems field.
func (r *queryResolver) DomainItems(ctx context.Context, filter *model.DefaultFilterInput) (*model.DomainItemList, error) {
	return r.DomainItemModule.API.DomainItems(ctx, filter)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
